2022-08-01 15:58:31,081 INFO    MainThread:9134 [wandb_setup.py:_flush():76] Configure stats pid to 9134
2022-08-01 15:58:31,081 INFO    MainThread:9134 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:58:31,081 INFO    MainThread:9134 [wandb_setup.py:_flush():76] Loading settings from /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/settings
2022-08-01 15:58:31,081 INFO    MainThread:9134 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-08-01 15:58:31,081 WARNING MainThread:9134 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:58:31,081 INFO    MainThread:9134 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:58:31,082 INFO    MainThread:9134 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155831-2yhn8gi2/logs/debug.log
2022-08-01 15:58:31,082 INFO    MainThread:9134 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155831-2yhn8gi2/logs/debug-internal.log
2022-08-01 15:58:31,084 INFO    MainThread:9134 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:58:31,084 INFO    MainThread:9134 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-01 15:58:31,086 INFO    MainThread:9134 [wandb_init.py:init():548] starting backend
2022-08-01 15:58:31,086 INFO    MainThread:9134 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:58:31,099 INFO    MainThread:9134 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:58:31,106 INFO    MainThread:9134 [backend.py:ensure_launched():222] started backend process with pid: 9160
2022-08-01 15:58:31,107 INFO    MainThread:9134 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:58:31,115 INFO    MainThread:9134 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:58:31,116 INFO    MainThread:9134 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:58:31,864 INFO    MainThread:9134 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:58:31,923 INFO    MainThread:9134 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:58:31,923 INFO    MainThread:9134 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:58:33,068 INFO    MainThread:9134 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 15:58:33,073 INFO    MainThread:9134 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 15:58:33,073 INFO    MainThread:9134 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 15:58:33,075 INFO    MainThread:9134 [wandb_run.py:_redirect():1827] Redirects installed.
2022-08-01 15:58:33,076 INFO    MainThread:9134 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 15:58:33,078 INFO    MainThread:9134 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_a/2yhn8gi2
2022-08-01 15:58:33,078 INFO    MainThread:9134 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 15:58:33,079 INFO    MainThread:9134 [wandb_run.py:_restore():1834] restore
2022-08-01 15:58:35,582 INFO    MainThread:9134 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:58:35,703 INFO    MainThread:9134 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:58:36,004 INFO    MainThread:9134 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:58:36,884 INFO    MainThread:9134 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5309
}

2022-08-01 15:58:36,986 INFO    MainThread:9134 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5693
}

