2022-08-01 19:57:13,806 INFO    Thread-15 :28568 [wandb_setup.py:_flush():76] Configure stats pid to 28568
2022-08-01 19:57:13,806 INFO    Thread-15 :28568 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 19:57:13,807 INFO    Thread-15 :28568 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 19:57:13,807 INFO    Thread-15 :28568 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_b', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'run_id': 'ub3f0idc', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-j85nql5s/config-ub3f0idc.yaml', 'sweep_id': 'j85nql5s'}
2022-08-01 19:57:13,807 WARNING Thread-15 :28568 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 19:57:13,807 INFO    Thread-15 :28568 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 19:57:13,807 INFO    Thread-15 :28568 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_195713-ub3f0idc/logs/debug.log
2022-08-01 19:57:13,807 INFO    Thread-15 :28568 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_195713-ub3f0idc/logs/debug-internal.log
2022-08-01 19:57:13,811 INFO    Thread-15 :28568 [wandb_init.py:init():495] calling init triggers
2022-08-01 19:57:13,811 INFO    Thread-15 :28568 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0005815668921378718, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
config: {}
2022-08-01 19:57:13,814 INFO    Thread-15 :28568 [wandb_init.py:init():548] starting backend
2022-08-01 19:57:13,814 INFO    Thread-15 :28568 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 19:57:13,823 INFO    Thread-15 :28568 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 19:57:13,843 INFO    Thread-15 :28568 [backend.py:ensure_launched():222] started backend process with pid: 37745
2022-08-01 19:57:13,845 INFO    Thread-15 :28568 [wandb_init.py:init():558] backend started and connected
2022-08-01 19:57:13,859 INFO    Thread-15 :28568 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0005815668921378718, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
2022-08-01 19:57:13,863 INFO    Thread-15 :28568 [wandb_init.py:init():634] updated telemetry
2022-08-01 19:57:13,864 INFO    Thread-15 :28568 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 19:57:14,678 INFO    Thread-15 :28568 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 19:57:14,779 INFO    Thread-15 :28568 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 19:57:14,779 INFO    Thread-15 :28568 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 19:57:15,879 INFO    Thread-15 :28568 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 19:57:15,883 INFO    Thread-15 :28568 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 19:57:15,883 INFO    Thread-15 :28568 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 19:57:15,883 ERROR   Thread-15 :28568 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 19:57:15,884 INFO    Thread-15 :28568 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 19:57:26,295 INFO    Thread-15 :28568 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_b/ub3f0idc
2022-08-01 19:57:26,296 INFO    Thread-15 :28568 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 19:57:26,298 INFO    Thread-15 :28568 [wandb_run.py:_restore():1834] restore
2022-08-01 19:57:26,301 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:57:26,603 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:57:26,713 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6039
}

2022-08-01 19:57:26,816 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6039
}

2022-08-01 19:57:26,918 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6039
}

2022-08-01 19:57:27,021 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6039
}

2022-08-01 19:57:27,124 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:27,226 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:27,329 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:27,432 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:27,535 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:27,638 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:28,337 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}

2022-08-01 19:57:28,889 INFO    Thread-15 :28568 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6039
  total_bytes: 6039
}
local_info {
}

2022-08-01 19:57:30,020 INFO    Thread-15 :28568 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 19:57:30,021 INFO    Thread-15 :28568 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 19:57:30,027 INFO    Thread-15 :28568 [wandb_run.py:_footer_sync_info():3055] logging synced files
