2022-08-01 15:54:37,551 INFO    Thread-3  :8718 [wandb_setup.py:_flush():76] Configure stats pid to 8718
2022-08-01 15:54:37,551 INFO    Thread-3  :8718 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:54:37,551 INFO    Thread-3  :8718 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 15:54:37,551 INFO    Thread-3  :8718 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_a', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': '838wzr8r', 'run_id': '5cb8qmy2', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-838wzr8r/config-5cb8qmy2.yaml'}
2022-08-01 15:54:37,551 WARNING Thread-3  :8718 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:54:37,551 INFO    Thread-3  :8718 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:54:37,552 INFO    Thread-3  :8718 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155437-5cb8qmy2/logs/debug.log
2022-08-01 15:54:37,552 INFO    Thread-3  :8718 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155437-5cb8qmy2/logs/debug-internal.log
2022-08-01 15:54:37,556 INFO    Thread-3  :8718 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:54:37,557 INFO    Thread-3  :8718 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 0.0003901089124081748, 'model': None}
config: {}
2022-08-01 15:54:37,560 INFO    Thread-3  :8718 [wandb_init.py:init():548] starting backend
2022-08-01 15:54:37,560 INFO    Thread-3  :8718 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:54:37,577 INFO    Thread-3  :8718 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:54:37,582 INFO    Thread-3  :8718 [backend.py:ensure_launched():222] started backend process with pid: 8749
2022-08-01 15:54:37,583 INFO    Thread-3  :8718 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:54:37,596 INFO    Thread-3  :8718 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 0.0003901089124081748, 'model': None}
2022-08-01 15:54:37,599 INFO    Thread-3  :8718 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:54:37,600 INFO    Thread-3  :8718 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:54:38,399 INFO    Thread-3  :8718 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:54:38,444 INFO    Thread-3  :8718 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:54:38,445 INFO    Thread-3  :8718 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:54:39,605 INFO    Thread-3  :8718 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 15:54:39,609 INFO    Thread-3  :8718 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 15:54:39,610 INFO    Thread-3  :8718 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 15:54:39,610 ERROR   Thread-3  :8718 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 15:54:39,612 INFO    Thread-3  :8718 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 15:54:39,614 INFO    Thread-3  :8718 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_a/5cb8qmy2
2022-08-01 15:54:39,614 INFO    Thread-3  :8718 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 15:54:39,615 INFO    Thread-3  :8718 [wandb_run.py:_restore():1834] restore
2022-08-01 15:54:39,829 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 527
}

2022-08-01 15:54:40,153 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:54:40,422 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5309
}

2022-08-01 15:54:40,525 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:54:40,627 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:54:40,733 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:54:40,835 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3643
  total_bytes: 5910
}

2022-08-01 15:54:40,938 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:41,040 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:41,143 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:41,246 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:41,348 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:42,330 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:54:42,866 INFO    Thread-3  :8718 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}
local_info {
}

2022-08-01 15:54:44,007 INFO    Thread-3  :8718 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 15:54:44,008 INFO    Thread-3  :8718 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 15:54:44,012 INFO    Thread-3  :8718 [wandb_run.py:_footer_sync_info():3055] logging synced files
