2022-08-01 15:49:33,712 INFO    Thread-3  :8254 [wandb_setup.py:_flush():76] Configure stats pid to 8254
2022-08-01 15:49:33,712 INFO    Thread-3  :8254 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:49:33,712 INFO    Thread-3  :8254 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 15:49:33,713 INFO    Thread-3  :8254 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_a', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': 'b7og7vn4', 'run_id': 'ekdaeimn', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-b7og7vn4/config-ekdaeimn.yaml'}
2022-08-01 15:49:33,713 WARNING Thread-3  :8254 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:49:33,713 INFO    Thread-3  :8254 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:49:33,713 INFO    Thread-3  :8254 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_154933-ekdaeimn/logs/debug.log
2022-08-01 15:49:33,713 INFO    Thread-3  :8254 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_154933-ekdaeimn/logs/debug-internal.log
2022-08-01 15:49:33,717 INFO    Thread-3  :8254 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:49:33,717 INFO    Thread-3  :8254 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 4, 'iteration': 5000, 'learning_rate': 0.0004287949148311756, 'model': None}
config: {}
2022-08-01 15:49:33,720 INFO    Thread-3  :8254 [wandb_init.py:init():548] starting backend
2022-08-01 15:49:33,720 INFO    Thread-3  :8254 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:49:33,741 INFO    Thread-3  :8254 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:49:33,747 INFO    Thread-3  :8254 [backend.py:ensure_launched():222] started backend process with pid: 8283
2022-08-01 15:49:33,748 INFO    Thread-3  :8254 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:49:33,761 INFO    Thread-3  :8254 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 32, 'IMS_PER_BATCH': 4, 'iteration': 5000, 'learning_rate': 0.0004287949148311756, 'model': None}
2022-08-01 15:49:33,764 INFO    Thread-3  :8254 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:49:33,765 INFO    Thread-3  :8254 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:49:34,688 INFO    Thread-3  :8254 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:49:34,744 INFO    Thread-3  :8254 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:49:34,744 INFO    Thread-3  :8254 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:49:36,170 INFO    Thread-3  :8254 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 15:49:36,175 INFO    Thread-3  :8254 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 15:49:36,176 INFO    Thread-3  :8254 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 15:49:36,176 ERROR   Thread-3  :8254 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 15:49:36,179 INFO    Thread-3  :8254 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 15:49:36,179 INFO    Thread-3  :8254 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_a/ekdaeimn
2022-08-01 15:49:36,179 INFO    Thread-3  :8254 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 15:49:36,180 INFO    Thread-3  :8254 [wandb_run.py:_restore():1834] restore
2022-08-01 15:49:36,417 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 527
}

2022-08-01 15:49:36,759 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:49:37,717 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:49:37,820 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:49:37,922 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:49:38,025 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5910
}

2022-08-01 15:49:38,127 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5309
  total_bytes: 5910
}

2022-08-01 15:49:38,235 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5309
  total_bytes: 5910
}

2022-08-01 15:49:38,338 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:38,441 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:38,544 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:38,646 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:38,749 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:39,041 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}

2022-08-01 15:49:39,576 INFO    Thread-3  :8254 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5910
  total_bytes: 5910
}
local_info {
}

2022-08-01 15:49:40,710 INFO    Thread-3  :8254 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 15:49:40,710 INFO    Thread-3  :8254 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 15:49:40,715 INFO    Thread-3  :8254 [wandb_run.py:_footer_sync_info():3055] logging synced files
