2022-08-01 15:59:51,499 INFO    MainThread:9359 [wandb_setup.py:_flush():76] Configure stats pid to 9359
2022-08-01 15:59:51,499 INFO    MainThread:9359 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:59:51,500 INFO    MainThread:9359 [wandb_setup.py:_flush():76] Loading settings from /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/settings
2022-08-01 15:59:51,500 INFO    MainThread:9359 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-08-01 15:59:51,500 WARNING MainThread:9359 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:59:51,500 INFO    MainThread:9359 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:59:51,500 INFO    MainThread:9359 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155951-3fo9vq1w/logs/debug.log
2022-08-01 15:59:51,500 INFO    MainThread:9359 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155951-3fo9vq1w/logs/debug-internal.log
2022-08-01 15:59:51,502 INFO    MainThread:9359 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:59:51,502 INFO    MainThread:9359 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-08-01 15:59:51,504 INFO    MainThread:9359 [wandb_init.py:init():548] starting backend
2022-08-01 15:59:51,504 INFO    MainThread:9359 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:59:51,516 INFO    MainThread:9359 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:59:51,522 INFO    MainThread:9359 [backend.py:ensure_launched():222] started backend process with pid: 9385
2022-08-01 15:59:51,524 INFO    MainThread:9359 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:59:51,533 INFO    MainThread:9359 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:59:51,534 INFO    MainThread:9359 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:59:52,265 INFO    MainThread:9359 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:59:52,319 INFO    MainThread:9359 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:59:52,319 INFO    MainThread:9359 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:59:52,641 WARNING MainThread:9359 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 711, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 234, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 440, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
