2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_setup.py:_flush():76] Configure stats pid to 1676533
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_b', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': 'ddys6s94', 'run_id': 'sdunvqc2', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-ddys6s94/config-sdunvqc2.yaml'}
2022-08-07 22:12:48,921 WARNING Thread-3  :1676533 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220807_221248-sdunvqc2/logs/debug.log
2022-08-07 22:12:48,921 INFO    Thread-3  :1676533 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220807_221248-sdunvqc2/logs/debug-internal.log
2022-08-07 22:12:48,923 INFO    Thread-3  :1676533 [wandb_init.py:init():495] calling init triggers
2022-08-07 22:12:48,923 INFO    Thread-3  :1676533 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 0.0006295183395592556, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
config: {}
2022-08-07 22:12:48,925 INFO    Thread-3  :1676533 [wandb_init.py:init():548] starting backend
2022-08-07 22:12:48,925 INFO    Thread-3  :1676533 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-07 22:12:48,943 INFO    Thread-3  :1676533 [backend.py:ensure_launched():217] starting backend process...
2022-08-07 22:12:48,953 INFO    Thread-3  :1676533 [backend.py:ensure_launched():222] started backend process with pid: 1676580
2022-08-07 22:12:48,954 INFO    Thread-3  :1676533 [wandb_init.py:init():558] backend started and connected
2022-08-07 22:12:48,972 INFO    Thread-3  :1676533 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 0.0006295183395592556, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
2022-08-07 22:12:48,976 INFO    Thread-3  :1676533 [wandb_init.py:init():634] updated telemetry
2022-08-07 22:12:48,977 INFO    Thread-3  :1676533 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-07 22:12:49,767 INFO    Thread-3  :1676533 [wandb_run.py:_on_init():1919] communicating current version
2022-08-07 22:12:49,805 INFO    Thread-3  :1676533 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-07 22:12:49,805 INFO    Thread-3  :1676533 [wandb_init.py:init():700] starting run threads in backend
2022-08-07 22:12:51,015 INFO    Thread-3  :1676533 [wandb_run.py:_console_start():1893] atexit reg
2022-08-07 22:12:51,021 INFO    Thread-3  :1676533 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-07 22:12:51,021 INFO    Thread-3  :1676533 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-07 22:12:51,022 ERROR   Thread-3  :1676533 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-07 22:12:51,023 INFO    Thread-3  :1676533 [wandb_init.py:init():732] run started, returning control to user process
2022-08-07 22:45:37,111 INFO    Thread-3  :1676533 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_b/sdunvqc2
2022-08-07 22:45:37,111 INFO    Thread-3  :1676533 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-07 22:45:37,114 INFO    Thread-3  :1676533 [wandb_run.py:_restore():1834] restore
2022-08-07 22:45:37,118 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-07 22:45:37,241 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-07 22:45:37,490 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-07 22:45:37,690 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6046
}

2022-08-07 22:45:37,792 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6046
}

2022-08-07 22:45:37,894 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6046
}

2022-08-07 22:45:37,996 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6046
}

2022-08-07 22:45:38,098 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,201 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,303 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,405 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,510 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,612 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:38,714 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:39,388 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}

2022-08-07 22:45:39,915 INFO    Thread-3  :1676533 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6046
  total_bytes: 6046
}
local_info {
}

2022-08-07 22:45:41,037 INFO    Thread-3  :1676533 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-07 22:45:41,038 INFO    Thread-3  :1676533 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-07 22:45:41,041 INFO    Thread-3  :1676533 [wandb_run.py:_footer_sync_info():3055] logging synced files
