2022-08-01 19:24:07,518 INFO    Thread-9  :28568 [wandb_setup.py:_flush():76] Configure stats pid to 28568
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_b', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'run_id': 'f99e0jlm', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-j85nql5s/config-f99e0jlm.yaml', 'sweep_id': 'j85nql5s'}
2022-08-01 19:24:07,519 WARNING Thread-9  :28568 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_192407-f99e0jlm/logs/debug.log
2022-08-01 19:24:07,519 INFO    Thread-9  :28568 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_192407-f99e0jlm/logs/debug-internal.log
2022-08-01 19:24:07,523 INFO    Thread-9  :28568 [wandb_init.py:init():495] calling init triggers
2022-08-01 19:24:07,523 INFO    Thread-9  :28568 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 3.727221486501231e-05, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
config: {}
2022-08-01 19:24:07,526 INFO    Thread-9  :28568 [wandb_init.py:init():548] starting backend
2022-08-01 19:24:07,527 INFO    Thread-9  :28568 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 19:24:07,536 INFO    Thread-9  :28568 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 19:24:07,557 INFO    Thread-9  :28568 [backend.py:ensure_launched():222] started backend process with pid: 30844
2022-08-01 19:24:07,559 INFO    Thread-9  :28568 [wandb_init.py:init():558] backend started and connected
2022-08-01 19:24:07,573 INFO    Thread-9  :28568 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 4, 'iteration': 1000, 'learning_rate': 3.727221486501231e-05, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
2022-08-01 19:24:07,578 INFO    Thread-9  :28568 [wandb_init.py:init():634] updated telemetry
2022-08-01 19:24:07,580 INFO    Thread-9  :28568 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 19:24:08,395 INFO    Thread-9  :28568 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 19:24:08,480 INFO    Thread-9  :28568 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 19:24:08,481 INFO    Thread-9  :28568 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 19:24:09,636 INFO    Thread-9  :28568 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 19:24:09,639 INFO    Thread-9  :28568 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 19:24:09,640 INFO    Thread-9  :28568 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 19:24:09,640 ERROR   Thread-9  :28568 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 19:24:09,641 INFO    Thread-9  :28568 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 19:57:05,522 INFO    Thread-9  :28568 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_b/f99e0jlm
2022-08-01 19:57:05,523 INFO    Thread-9  :28568 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-01 19:57:05,527 INFO    Thread-9  :28568 [wandb_run.py:_restore():1834] restore
2022-08-01 19:57:05,531 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:57:05,902 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:57:06,442 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6045
}

2022-08-01 19:57:06,544 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6045
}

2022-08-01 19:57:06,647 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6045
}

2022-08-01 19:57:06,749 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6045
}

2022-08-01 19:57:06,852 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3556
  total_bytes: 6045
}

2022-08-01 19:57:06,955 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:07,057 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:07,160 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:07,264 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:07,367 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:08,152 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}

2022-08-01 19:57:08,715 INFO    Thread-9  :28568 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6045
  total_bytes: 6045
}
local_info {
}

2022-08-01 19:57:09,842 INFO    Thread-9  :28568 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 19:57:09,842 INFO    Thread-9  :28568 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 19:57:09,844 INFO    Thread-9  :28568 [wandb_run.py:_footer_sync_info():3055] logging synced files
