2022-08-01 19:14:32,118 INFO    Thread-3  :28526 [wandb_setup.py:_flush():76] Configure stats pid to 28526
2022-08-01 19:14:32,118 INFO    Thread-3  :28526 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 19:14:32,118 INFO    Thread-3  :28526 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 19:14:32,118 INFO    Thread-3  :28526 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_c', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': 'lvrbbbhk', 'run_id': 'fglaujdy', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-lvrbbbhk/config-fglaujdy.yaml'}
2022-08-01 19:14:32,118 WARNING Thread-3  :28526 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 19:14:32,119 INFO    Thread-3  :28526 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 19:14:32,119 INFO    Thread-3  :28526 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_191432-fglaujdy/logs/debug.log
2022-08-01 19:14:32,119 INFO    Thread-3  :28526 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_191432-fglaujdy/logs/debug-internal.log
2022-08-01 19:14:32,122 INFO    Thread-3  :28526 [wandb_init.py:init():495] calling init triggers
2022-08-01 19:14:32,123 INFO    Thread-3  :28526 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 2, 'iteration': 300, 'learning_rate': 0.000847703543715697, 'model': 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'}
config: {}
2022-08-01 19:14:32,125 INFO    Thread-3  :28526 [wandb_init.py:init():548] starting backend
2022-08-01 19:14:32,126 INFO    Thread-3  :28526 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 19:14:32,147 INFO    Thread-3  :28526 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 19:14:32,158 INFO    Thread-3  :28526 [backend.py:ensure_launched():222] started backend process with pid: 28603
2022-08-01 19:14:32,159 INFO    Thread-3  :28526 [wandb_init.py:init():558] backend started and connected
2022-08-01 19:14:32,173 INFO    Thread-3  :28526 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 2, 'iteration': 300, 'learning_rate': 0.000847703543715697, 'model': 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'}
2022-08-01 19:14:32,177 INFO    Thread-3  :28526 [wandb_init.py:init():634] updated telemetry
2022-08-01 19:14:32,178 INFO    Thread-3  :28526 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 19:14:33,010 INFO    Thread-3  :28526 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 19:14:33,051 INFO    Thread-3  :28526 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 19:14:33,051 INFO    Thread-3  :28526 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 19:14:34,190 INFO    Thread-3  :28526 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 19:14:34,193 INFO    Thread-3  :28526 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 19:14:34,193 INFO    Thread-3  :28526 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 19:14:34,193 ERROR   Thread-3  :28526 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 19:14:34,194 INFO    Thread-3  :28526 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 19:16:45,710 INFO    Thread-3  :28526 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_c/fglaujdy
2022-08-01 19:16:45,710 INFO    Thread-3  :28526 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-01 19:16:45,712 INFO    Thread-3  :28526 [wandb_run.py:_restore():1834] restore
2022-08-01 19:16:45,717 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:16:46,098 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 19:16:47,091 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5400
}

2022-08-01 19:16:47,193 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6040
}

2022-08-01 19:16:47,295 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6040
}

2022-08-01 19:16:47,398 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 6040
}

2022-08-01 19:16:47,500 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3551
  total_bytes: 6040
}

2022-08-01 19:16:47,602 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:47,705 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:47,808 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:47,910 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:48,013 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:48,763 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}

2022-08-01 19:16:49,325 INFO    Thread-3  :28526 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6040
  total_bytes: 6040
}
local_info {
}

2022-08-01 19:16:50,460 INFO    Thread-3  :28526 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 19:16:50,461 INFO    Thread-3  :28526 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 19:16:50,464 INFO    Thread-3  :28526 [wandb_run.py:_footer_sync_info():3055] logging synced files
