2022-08-02 01:52:04,961 INFO    Thread-33 :82543 [wandb_setup.py:_flush():76] Configure stats pid to 82543
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_eval', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'run_id': 'j4emh08y', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-n4vitr42/config-j4emh08y.yaml', 'sweep_id': 'n4vitr42'}
2022-08-02 01:52:04,962 WARNING Thread-33 :82543 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220802_015204-j4emh08y/logs/debug.log
2022-08-02 01:52:04,962 INFO    Thread-33 :82543 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220802_015204-j4emh08y/logs/debug-internal.log
2022-08-02 01:52:04,966 INFO    Thread-33 :82543 [wandb_init.py:init():495] calling init triggers
2022-08-02 01:52:04,966 INFO    Thread-33 :82543 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 128, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0008465054974690211, 'model': 'COCO-Detection/rpn_R_50_FPN_1x.yaml'}
config: {}
2022-08-02 01:52:04,969 INFO    Thread-33 :82543 [wandb_init.py:init():548] starting backend
2022-08-02 01:52:04,970 INFO    Thread-33 :82543 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-02 01:52:04,979 INFO    Thread-33 :82543 [backend.py:ensure_launched():217] starting backend process...
2022-08-02 01:52:05,003 INFO    Thread-33 :82543 [backend.py:ensure_launched():222] started backend process with pid: 103906
2022-08-02 01:52:05,004 INFO    Thread-33 :82543 [wandb_init.py:init():558] backend started and connected
2022-08-02 01:52:05,018 INFO    Thread-33 :82543 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 128, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0008465054974690211, 'model': 'COCO-Detection/rpn_R_50_FPN_1x.yaml'}
2022-08-02 01:52:05,023 INFO    Thread-33 :82543 [wandb_init.py:init():634] updated telemetry
2022-08-02 01:52:05,024 INFO    Thread-33 :82543 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-02 01:52:05,871 INFO    Thread-33 :82543 [wandb_run.py:_on_init():1919] communicating current version
2022-08-02 01:52:05,920 INFO    Thread-33 :82543 [wandb_run.py:_on_init():1923] got version response 
2022-08-02 01:52:05,920 INFO    Thread-33 :82543 [wandb_init.py:init():700] starting run threads in backend
2022-08-02 01:52:07,035 INFO    Thread-33 :82543 [wandb_run.py:_console_start():1893] atexit reg
2022-08-02 01:52:07,039 INFO    Thread-33 :82543 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-02 01:52:07,039 INFO    Thread-33 :82543 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-02 01:52:07,039 ERROR   Thread-33 :82543 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-02 01:52:07,040 INFO    Thread-33 :82543 [wandb_init.py:init():732] run started, returning control to user process
2022-08-02 03:19:07,181 INFO    Thread-33 :82543 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_eval/j4emh08y
2022-08-02 03:19:07,181 INFO    Thread-33 :82543 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-08-02 03:19:07,186 INFO    Thread-33 :82543 [wandb_run.py:_restore():1834] restore
2022-08-02 03:19:07,189 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 530
}

2022-08-02 03:19:07,566 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 530
}

2022-08-02 03:19:07,668 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 6041
}

2022-08-02 03:19:07,771 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 6041
}

2022-08-02 03:19:07,877 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 6041
}

2022-08-02 03:19:07,979 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 530
  total_bytes: 6041
}

2022-08-02 03:19:08,082 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:08,184 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:08,287 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:08,389 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:08,491 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:08,594 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:09,688 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}

2022-08-02 03:19:10,242 INFO    Thread-33 :82543 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6041
  total_bytes: 6041
}
local_info {
}

2022-08-02 03:19:11,365 INFO    Thread-33 :82543 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-02 03:19:11,366 INFO    Thread-33 :82543 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-02 03:19:11,371 INFO    Thread-33 :82543 [wandb_run.py:_footer_sync_info():3055] logging synced files
